FROM delner/nginx-unicorn-rails:1.10.1-2.3.1

# Set Nginx site configuration
ADD config/nginx/development.conf /etc/nginx/sites-enabled/default

WORKDIR /tmp
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock
RUN bundle install -j 4

WORKDIR /app

# Automatically start the web server
CMD ./bin/start.sh

EXPOSE 80