db:
  image: postgres:9.5.3
  environment:
  - POSTGRES_PASSWORD=123456
  - POSTGRES_USER=postgres
  - POSTGRES_DB=news_presenter_development

redis:
  image: redis
  ports:
    - "6379"

web:
  build: .
  dockerfile: Dockerfile-dev
  command: ./bin/start.sh
  volumes:
    - .:/app
  environment:
    - DB_USERNAME=postgres
    - DB_PASSWORD=123456
  links:
    - db
    - redis
  ports:
    - "80:80"

sidekiq:
 build: .
 command: bundle exec sidekiq -q default -e production -p tmp/pids/sidekiq.pid -L log/sidekiq.log -d
 links:
   - db
   - redis
 volumes:
   - .:/usr/src/service